"use client";

import Footer from "@/components/Footer";
import Navigation from "@/components/Navigation";
import ImageBackground from "@/components/ImageBackground";
import { motion } from "framer-motion";
import Link from "next/link";

export default function LearnMorePage() {
  const features = [
    {
      icon: (
        <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
        </svg>
      ),
      title: "Advanced Analytics",
      description: "Deep insights into your health patterns with trend analysis, correlations, and personalized recommendations based on your unique data.",
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M13 10V3L4 14h7v7l9-11h-7z" />
        </svg>
      ),
      title: "AI Workout Coaching",
      description: "Get personalized workout plans generated by AI that adapt to your goals, fitness level, available equipment, and recovery needs.",
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
        </svg>
      ),
      title: "Food Vision",
      description: "Snap a photo of your meal and let Delta analyze it instantly. Track nutrition effortlessly with AI-powered food recognition.",
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
        </svg>
      ),
      title: "Unlimited Conversations",
      description: "Chat with Delta as much as you need. No daily limits, no restrictions. Your personal health companion is always available.",
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
      ),
      title: "Data Export",
      description: "Export your health data anytime. Your data belongs to you, and you can take it with you wherever you go.",
    },
    {
      icon: (
        <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
        </svg>
      ),
      title: "Smart Insights",
      description: "Receive proactive insights about your health trends. Delta learns your patterns and surfaces relevant observations automatically.",
    },
  ];

  return (
    <>
      <Navigation />
      <main className="min-h-screen">
        {/* Hero with Background Image */}
        <ImageBackground
          src="/images/hero/aerial-glaciers.jpg"
          alt="Premium features"
          overlay="medium"

          priority
          className="min-h-[55vh] flex items-center justify-center"
        >
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: false, amount: 0.45 }}
            transition={{ duration: 0.5 }}
            className="text-center max-w-3xl mx-auto px-8 pt-32 pb-16"
          >
            <motion.span
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: false, amount: 0.45 }}
              transition={{ delay: 0.1 }}
              className="text-primary font-medium text-sm tracking-wider uppercase"
            >
              Premium Features
            </motion.span>
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: false, amount: 0.45 }}
              transition={{ delay: 0.15, duration: 0.5 }}
              className="text-5xl md:text-6xl font-bold mt-4 mb-6"
            >
              Unlock Your Full
              <br />
              <span className="text-primary">Health Potential</span>
            </motion.h1>
            <motion.p
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: false, amount: 0.45 }}
              transition={{ delay: 0.2 }}
              className="text-muted text-lg leading-relaxed"
            >
              Delta Premium gives you access to advanced features designed to help you
              achieve your health goals faster and more effectively.
            </motion.p>
          </motion.div>
        </ImageBackground>

        {/* Features Grid */}
        <div className="max-w-5xl mx-auto px-8 py-20">
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: false, amount: 0.3 }}
                transition={{ delay: index * 0.1 }}
                className="p-6 bg-card rounded-2xl border border-border hover:border-primary/30 transition-colors"
              >
                <div className="w-14 h-14 rounded-xl bg-primary/10 text-primary flex items-center justify-center mb-4">
                  {feature.icon}
                </div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-muted text-sm leading-relaxed">
                  {feature.description}
                </p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* How It Works with Background */}
        <ImageBackground
          src="/images/hero/ocean-mountains.jpg"
          alt="How it works"
          overlay="heavy"

          className="py-20"
        >
          <div className="max-w-4xl mx-auto px-8">
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: false, amount: 0.4 }}
              className="text-center mb-12"
            >
              <h2 className="text-3xl font-bold mb-4">How Delta Works</h2>
              <p className="text-muted max-w-2xl mx-auto">
                Delta learns from your conversations and health data to provide increasingly
                personalized guidance over time.
              </p>
            </motion.div>

            <div className="grid md:grid-cols-3 gap-8">
              {[
                {
                  step: "1",
                  title: "Track Naturally",
                  description: "Just chat with Delta about your meals, workouts, sleep, and how you're feeling. No tedious manual logging required.",
                },
                {
                  step: "2",
                  title: "Build Context",
                  description: "Delta remembers everything and builds a comprehensive understanding of your health patterns, goals, and preferences.",
                },
                {
                  step: "3",
                  title: "Get Insights",
                  description: "Receive personalized insights, recommendations, and coaching based on your unique health profile.",
                },
              ].map((item, index) => (
                <motion.div
                  key={item.step}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: false, amount: 0.4 }}
                  transition={{ delay: index * 0.15 }}
                  className="text-center p-6 bg-card/60 backdrop-blur-sm rounded-2xl"
                >
                  <div className="w-12 h-12 rounded-full bg-primary text-white font-bold text-xl flex items-center justify-center mx-auto mb-4">
                    {item.step}
                  </div>
                  <h3 className="font-semibold mb-2">{item.title}</h3>
                  <p className="text-muted text-sm">{item.description}</p>
                </motion.div>
              ))}
            </div>
          </div>
        </ImageBackground>

        {/* CTA with Background */}
        <ImageBackground
          src="/images/hero/sunset-shore.jpg"
          alt="Get started"
          overlay="heavy"

          className="py-20"
        >
          <motion.div
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: false, amount: 0.4 }}
            className="max-w-3xl mx-auto px-8 text-center"
          >
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Ready to Transform Your Health?
            </h2>
            <p className="text-muted mb-8 max-w-xl mx-auto">
              Download Delta and start your journey toward better health with AI-powered
              guidance that understands you.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <motion.a
                href="https://apps.apple.com/app/delta"
                target="_blank"
                rel="noopener noreferrer"
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                className="flex items-center justify-center gap-2 px-6 py-3 bg-black text-white rounded-xl font-medium"
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12.152 6.896c-.948 0-2.415-1.078-3.96-1.04-2.04.027-3.91 1.183-4.961 3.014-2.117 3.675-.546 9.103 1.519 12.09 1.013 1.454 2.208 3.09 3.792 3.039 1.52-.065 2.09-.987 3.935-.987 1.831 0 2.35.987 3.96.948 1.637-.026 2.676-1.48 3.676-2.948 1.156-1.688 1.636-3.325 1.662-3.415-.039-.013-3.182-1.221-3.22-4.857-.026-3.04 2.48-4.494 2.597-4.559-1.429-2.09-3.623-2.324-4.39-2.376-2-.156-3.675 1.09-4.61 1.09zM15.53 3.83c.843-1.012 1.4-2.427 1.245-3.83-1.207.052-2.662.805-3.532 1.818-.78.896-1.454 2.338-1.273 3.714 1.338.104 2.715-.688 3.559-1.701" />
                </svg>
                Download for iOS
              </motion.a>
              <Link href="/signup">
                <motion.span
                  whileHover={{ scale: 1.05 }}
                  whileTap={{ scale: 0.95 }}
                  className="flex items-center justify-center gap-2 px-6 py-3 border border-white/20 bg-white/10 backdrop-blur-sm rounded-xl font-medium hover:bg-white/20 transition-colors"
                >
                  Create Free Account
                </motion.span>
              </Link>
            </div>
          </motion.div>
        </ImageBackground>
      </main>
      <Footer />
    </>
  );
}
